export const patientColumns = [
  "id",
  "created_at",
  "updated_at",
  "status",
  "patient_name",
  "cpf",
  "sus_card",
  "birth_date",
  "phone",
  "email",
  "city",
  "state",
  "medical_request_date",
  "audiometry_date",
  "hearing_loss",
  "documentation_notes",
  "test_date",
  "audiologist_name",
  "test_result",
  "patient_approved",
  "order_date",
  "factory_order_number",
  "device_side",
  "device_brand",
  "device_model",
  "right_device_code",
  "left_device_code",
  "accessory_codes",
  "factory_value_cents",
  "patient_value_cents",
  "arrival_date",
  "adaptation_date",
  "notes"
];

export function normalizePatient(input) {
  const get = (key) => {
    const value = input[key];
    return value === "" || value === undefined ? null : value;
  };

  return {
    status: get("status") || "documentacao_recebida",
    patient_name: get("patient_name"),
    cpf: get("cpf"),
    sus_card: get("sus_card"),
    birth_date: get("birth_date"),
    phone: get("phone"),
    email: get("email"),
    city: get("city"),
    state: get("state"),
    medical_request_date: get("medical_request_date"),
    audiometry_date: get("audiometry_date"),
    hearing_loss: get("hearing_loss"),
    documentation_notes: get("documentation_notes"),
    test_date: get("test_date"),
    audiologist_name: get("audiologist_name"),
    test_result: get("test_result"),
    patient_approved: Boolean(input.patient_approved),
    order_date: get("order_date"),
    factory_order_number: get("factory_order_number"),
    device_side: get("device_side") || "bilateral",
    device_brand: get("device_brand"),
    device_model: get("device_model"),
    right_device_code: get("right_device_code"),
    left_device_code: get("left_device_code"),
    accessory_codes: get("accessory_codes"),
    factory_value_cents: Number(input.factory_value_cents || 0),
    patient_value_cents: Number(input.patient_value_cents || 0),
    arrival_date: get("arrival_date"),
    adaptation_date: get("adaptation_date"),
    notes: get("notes")
  };
}
